[package]
name = "hot_dog"
version = "0.1.0"
authors = ["950288 <950288s@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.3", features = ["router", "fullstack", "web"] }
indexmap = { version = "2.7.1", optional = true }
once_cell = { version = "1.20.3", optional = true }
candle-core = { version = "0.9.0-alpha.1", optional = true }
getrandom = { version = "0.3.0", features = ["wasm_js"], optional = true }
web-sys = { version = "0.3.77", optional = true }
anyhow = { version = "1.0.97", optional = true }

[features]
web = ["dioxus/web", "dep:indexmap", "dep:once_cell", "dep:candle-core", "dep:getrandom", "dep:web-sys", "dep:anyhow"]
server = ["dioxus/server", "dep:candle-core", "dep:getrandom"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
